[client]
toolbarMode = "minimal"

[server]
runOnSave = true

[theme]
base = "light"
primaryColor = "#5540af"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
font = "sans serif"
